# fly.toml app configuration file generated for cloudy-server on 2025-06-12T20:27:35+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cloudy-server'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.proxy]]
  timeout = "1200s"
  idle_timeout = "600s"  # 5 minutes idle timeout
  read_timeout = "600s"  # 5 minutes read timeout
  write_timeout = "600s"  # 5 minutes write timeout

[http_service.proxy.body_size_limit]
  max_size = "500mb"  # Adjust based on your file upload needs

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  PORT = "3000"
  NODE_ENV = "production"
